const UNTITLED = 'untitled';
const UNTITLED_PHRASE = '홈페이지 참조';

const HOME_CATEGORY_NAME = 'HOME';
const HOME_CATEGORY_INFO = {
  name: 'ALL',
}

const SEARCH_CATEGORY_NAME = 'SEARCH';

export { UNTITLED, UNTITLED_PHRASE, HOME_CATEGORY_NAME, HOME_CATEGORY_INFO, SEARCH_CATEGORY_NAME };
